// This file was auto-generated by ML.NET Model Builder. 

using System;
using ModeloPredictivoML.Model;

namespace ModeloPredictivoML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                TipoArchivo = @"Archivo",
                BajarSistema = @"Si",
                Sistema = @"PrometeusCliente",
                Distribucion = @"PrometeusCliente",
                Extension = @"xml",
                Fecha = @"2019-01-03",
                Anio = @"2019",
                Mes = @"1",
                Dia = @"3",
                DiaSemana = @"Thursday",
                TipoDia = @"N",
                Solicitante = @"freirejj",
                TipoDeploy = @"Normal",
                Responsable = @"rivadeneiraw"
            };
            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Resultado with predicted Resultado from sample data...\n\n");
            Console.WriteLine($"TipoArchivo: {sampleData.TipoArchivo}");
            Console.WriteLine($"BajarSistema: {sampleData.BajarSistema}");
            Console.WriteLine($"Sistema: {sampleData.Sistema}");
            Console.WriteLine($"Distribucion: {sampleData.Distribucion}");
            Console.WriteLine($"Extension: {sampleData.Extension}");
            Console.WriteLine($"Fecha: {sampleData.Fecha}");
            Console.WriteLine($"Anio: {sampleData.Anio}");
            Console.WriteLine($"Mes: {sampleData.Mes}");
            Console.WriteLine($"Dia: {sampleData.Dia}");
            Console.WriteLine($"DiaSemana: {sampleData.DiaSemana}");
            Console.WriteLine($"TipoDia: {sampleData.TipoDia}");
            Console.WriteLine($"Solicitante: {sampleData.Solicitante}");
            Console.WriteLine($"TipoDeploy: {sampleData.TipoDeploy}");
            Console.WriteLine($"Responsable: {sampleData.Responsable}");
            Console.WriteLine($"\n\nPredicted Resultado value {predictionResult.Prediction} \nPredicted Resultado scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
