//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.srProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srProxy.IwcfChatBot")]
    public interface IwcfChatBot {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfChatBot/opciones", ReplyAction="http://tempuri.org/IwcfChatBot/opcionesResponse")]
        DTO.dtoOpcion[] opciones(DTO.parOpcion _par);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfChatBot/cargarInstancias", ReplyAction="http://tempuri.org/IwcfChatBot/cargarInstanciasResponse")]
        DTO.dtoInstancia[] cargarInstancias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwcfChatBot/cargarMensaje", ReplyAction="http://tempuri.org/IwcfChatBot/cargarMensajeResponse")]
        string cargarMensaje(DTO.dtoOpcion _dtoOpcion, DTO.dtoInstancia _dtoInstancia, string _strUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwcfChatBotChannel : GUI.srProxy.IwcfChatBot, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwcfChatBotClient : System.ServiceModel.ClientBase<GUI.srProxy.IwcfChatBot>, GUI.srProxy.IwcfChatBot {
        
        public IwcfChatBotClient() {
        }
        
        public IwcfChatBotClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwcfChatBotClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfChatBotClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwcfChatBotClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DTO.dtoOpcion[] opciones(DTO.parOpcion _par) {
            return base.Channel.opciones(_par);
        }
        
        public DTO.dtoInstancia[] cargarInstancias() {
            return base.Channel.cargarInstancias();
        }
        
        public string cargarMensaje(DTO.dtoOpcion _dtoOpcion, DTO.dtoInstancia _dtoInstancia, string _strUsuario) {
            return base.Channel.cargarMensaje(_dtoOpcion, _dtoInstancia, _strUsuario);
        }
    }
}
