// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ModeloPredictivoML.Model
{
    public class ModelInput
    {
        [ColumnName("TipoArchivo"), LoadColumn(0)]
        public string TipoArchivo { get; set; }


        [ColumnName("BajarSistema"), LoadColumn(1)]
        public string BajarSistema { get; set; }


        [ColumnName("Sistema"), LoadColumn(2)]
        public string Sistema { get; set; }


        [ColumnName("Distribucion"), LoadColumn(3)]
        public string Distribucion { get; set; }


        [ColumnName("Extension"), LoadColumn(4)]
        public string Extension { get; set; }


        [ColumnName("Fecha"), LoadColumn(5)]
        public string Fecha { get; set; }


        [ColumnName("Anio"), LoadColumn(6)]
        public string Anio { get; set; }


        [ColumnName("Mes"), LoadColumn(7)]
        public string Mes { get; set; }


        [ColumnName("Dia"), LoadColumn(8)]
        public string Dia { get; set; }


        [ColumnName("DiaSemana"), LoadColumn(9)]
        public string DiaSemana { get; set; }


        [ColumnName("TipoDia"), LoadColumn(10)]
        public string TipoDia { get; set; }


        [ColumnName("Solicitante"), LoadColumn(11)]
        public string Solicitante { get; set; }


        [ColumnName("TipoDeploy"), LoadColumn(12)]
        public string TipoDeploy { get; set; }


        [ColumnName("Responsable"), LoadColumn(13)]
        public string Responsable { get; set; }


        [ColumnName("Resultado"), LoadColumn(14)]
        public string Resultado { get; set; }


    }
}
